
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/fsm 

module fsm_final(clk, rst, nfc, card_active, fund_enough, maintenance,
     monthly, open, reduce_bal, disp, sound);
  input clk, rst, nfc, card_active, fund_enough, maintenance, monthly;
  output open, reduce_bal;
  output [2:0] disp;
  output [1:0] sound;
  wire clk, rst, nfc, card_active, fund_enough, maintenance, monthly;
  wire open, reduce_bal;
  wire [2:0] disp;
  wire [1:0] sound;
  wire [10:0] state;
  wire [2:0] count;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_110, n_112, n_122, n_123, n_124, n_125;
  DFFHQX1 \state_reg[2] (.CK (clk), .D (n_96), .Q (state[2]));
  NAND3BXL g4089(.AN (n_88), .B (n_36), .C (n_94), .Y (n_96));
  DFFHQX1 \state_reg[3] (.CK (clk), .D (n_95), .Q (state[3]));
  AOI211XL g4091(.A0 (n_71), .A1 (n_82), .B0 (rst), .C0 (n_93), .Y
       (n_95));
  AOI221X1 g4092(.A0 (card_active), .A1 (n_52), .B0 (n_91), .B1 (open),
       .C0 (n_59), .Y (n_94));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_92), .Q (state[0]));
  OAI22X1 g4097(.A0 (n_90), .A1 (open), .B0 (maintenance), .B1 (n_64),
       .Y (n_93));
  NAND4XL g4090(.A (n_83), .B (n_87), .C (n_55), .D (n_79), .Y (n_92));
  DFFHQX1 \state_reg[6] (.CK (clk), .D (n_89), .Q (disp[0]));
  DFFHQX1 \state_reg[8] (.CK (clk), .D (n_86), .Q (disp[2]));
  DFFHQX1 \state_reg[5] (.CK (clk), .D (n_85), .Q (open));
  INVX1 g4108(.A (n_90), .Y (n_91));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_77), .Q (state[1]));
  DFFHQX1 \state_reg[7] (.CK (clk), .D (n_80), .Q (disp[1]));
  NAND3BXL g4109(.AN (n_15), .B (n_78), .C (n_81), .Y (n_90));
  NAND2BX1 g4099(.AN (n_88), .B (n_87), .Y (n_89));
  NAND2BXL g4101(.AN (n_88), .B (n_84), .Y (n_86));
  NAND2X1 g4105(.A (n_84), .B (n_83), .Y (n_85));
  NOR4X1 g4106(.A (n_57), .B (n_40), .C (n_61), .D (n_81), .Y (n_82));
  NAND2BXL g4100(.AN (n_88), .B (n_73), .Y (n_80));
  AOI21X1 g4102(.A0 (n_78), .A1 (n_70), .B0 (n_69), .Y (n_79));
  NAND3BXL g4103(.AN (n_74), .B (n_83), .C (n_75), .Y (n_77));
  DFFHQX1 \state_reg[9] (.CK (clk), .D (n_76), .Q (sound[0]));
  NOR2X1 g4110(.A (n_53), .B (n_68), .Y (n_87));
  AOI21X1 g4112(.A0 (n_58), .A1 (n_72), .B0 (n_50), .Y (n_84));
  INVX1 g4113(.A (n_75), .Y (n_76));
  OAI211X1 g4116(.A0 (rst), .A1 (n_51), .B0 (n_73), .C0 (n_54), .Y
       (n_74));
  NAND3BXL g4118(.AN (n_72), .B (n_43), .C (n_122), .Y (n_81));
  DFFHQX1 \state_reg[10] (.CK (clk), .D (n_66), .Q (sound[1]));
  AOI21X1 g4107(.A0 (n_63), .A1 (n_71), .B0 (rst), .Y (n_88));
  NAND2X1 g4111(.A (n_65), .B (n_71), .Y (n_70));
  DFFHQX1 \state_reg[4] (.CK (clk), .D (n_56), .Q (reduce_bal));
  AOI211XL g4114(.A0 (n_78), .A1 (n_62), .B0 (n_69), .C0 (n_125), .Y
       (n_75));
  OAI22X1 g4119(.A0 (n_46), .A1 (n_67), .B0 (monthly), .B1 (n_49), .Y
       (n_68));
  OAI2BB1X1 g4121(.A0N (n_26), .A1N (n_48), .B0 (n_67), .Y (n_72));
  INVX1 g4129(.A (n_83), .Y (n_66));
  NAND2BX1 g4115(.AN (n_64), .B (maintenance), .Y (n_65));
  OAI21X1 g4117(.A0 (maintenance), .A1 (n_62), .B0 (n_60), .Y (n_63));
  NAND2BXL g4122(.AN (n_60), .B (n_44), .Y (n_61));
  AOI21X1 g4130(.A0 (monthly), .A1 (n_47), .B0 (n_59), .Y (n_83));
  AOI22X1 g4132(.A0 (n_58), .A1 (n_42), .B0 (n_78), .B1 (n_57), .Y
       (n_73));
  INVX1 g4135(.A (n_55), .Y (n_56));
  INVX1 g4139(.A (n_53), .Y (n_54));
  NOR2BX1 g4142(.AN (n_52), .B (card_active), .Y (n_69));
  NAND3BXL g4143(.AN (maintenance), .B (nfc), .C (n_41), .Y (n_51));
  INVX1 g4126(.A (n_49), .Y (n_50));
  NAND4X1 g4131(.A (disp[0]), .B (state[0]), .C (n_38), .D (n_48), .Y
       (n_67));
  NAND3BXL g4136(.AN (monthly), .B (fund_enough), .C (n_47), .Y (n_55));
  OAI22X1 g4140(.A0 (n_46), .A1 (n_122), .B0 (rst), .B1 (n_44), .Y
       (n_53));
  INVX1 g4145(.A (n_42), .Y (n_43));
  AOI2BB1XL g4123(.A0N (nfc), .A1N (n_110), .B0 (n_41), .Y (n_64));
  NAND2X1 g4127(.A (n_78), .B (n_40), .Y (n_49));
  NAND2BX1 g4128(.AN (n_41), .B (n_39), .Y (n_60));
  NOR4X1 g4133(.A (rst), .B (disp[0]), .C (n_38), .D (n_33), .Y (n_59));
  NOR4X1 g4146(.A (disp[2]), .B (open), .C (n_35), .D (n_27), .Y
       (n_42));
  NOR3X1 g4152(.A (rst), .B (n_35), .C (n_34), .Y (n_52));
  NOR2BX1 g4125(.AN (nfc), .B (n_110), .Y (n_62));
  NOR2X1 g4149(.A (state[1]), .B (n_30), .Y (n_48));
  NOR2X1 g4156(.A (state[1]), .B (n_34), .Y (n_41));
  NOR4X1 g4137(.A (sound[0]), .B (n_3), .C (n_35), .D (n_123), .Y
       (n_40));
  NAND4XL g4138(.A (disp[2]), .B (n_35), .C (n_31), .D (n_21), .Y
       (n_39));
  NAND3X1 g4144(.A (disp[2]), .B (disp[1]), .C (n_19), .Y (n_71));
  NAND4XL g4154(.A (n_78), .B (state[2]), .C (n_29), .D (n_32), .Y
       (n_36));
  NAND3BXL g4159(.AN (n_20), .B (n_13), .C (n_32), .Y (n_33));
  NOR4X1 g4155(.A (state[2]), .B (n_35), .C (n_31), .D (n_14), .Y
       (n_57));
  NAND4XL g4157(.A (disp[2]), .B (open), .C (n_23), .D (n_25), .Y
       (n_30));
  NAND2X1 g4163(.A (n_29), .B (n_28), .Y (n_34));
  NAND3X1 g4164(.A (disp[1]), .B (n_26), .C (n_25), .Y (n_27));
  NAND3BXL g4170(.AN (n_18), .B (n_12), .C (n_29), .Y (n_44));
  DFFHQX1 \count_reg[2] (.CK (clk), .D (n_22), .Q (count[2]));
  INVX1 g4147(.A (n_46), .Y (n_58));
  NOR2X1 g4150(.A (n_124), .B (n_5), .Y (n_22));
  NOR4X1 g4160(.A (sound[1]), .B (n_23), .C (n_20), .D (n_17), .Y
       (n_21));
  NOR4X1 g4161(.A (sound[1]), .B (state[0]), .C (n_18), .D (n_17), .Y
       (n_19));
  NOR2X1 g4167(.A (state[2]), .B (n_16), .Y (n_28));
  NOR2X1 g4168(.A (state[1]), .B (n_16), .Y (n_32));
  DFFQXL \count_reg[1] (.CK (clk), .D (n_6), .Q (count[1]));
  DFFHQX1 \count_reg[0] (.CK (clk), .D (n_7), .Q (count[0]));
  NAND2X1 g4148(.A (n_78), .B (n_15), .Y (n_46));
  NAND4XL g4171(.A (state[0]), .B (n_8), .C (n_13), .D (n_12), .Y
       (n_14));
  NOR3X1 g4177(.A (sound[1]), .B (sound[0]), .C (n_124), .Y (n_25));
  AND2XL g4174(.A (n_13), .B (n_26), .Y (n_29));
  NAND2X1 g4173(.A (n_31), .B (n_12), .Y (n_16));
  NOR3BXL g4178(.AN (n_8), .B (state[3]), .C (n_20), .Y (n_9));
  NOR2X1 g4180(.A (n_124), .B (count[0]), .Y (n_7));
  NOR2X1 g4169(.A (n_124), .B (n_2), .Y (n_6));
  XNOR2X1 g4165(.A (count[2]), .B (n_4), .Y (n_5));
  NOR2X1 g4166(.A (count[2]), .B (n_4), .Y (n_15));
  NAND4X1 g4176(.A (state[3]), .B (disp[0]), .C (n_38), .D (n_3), .Y
       (n_17));
  NOR2BX1 g4179(.AN (n_8), .B (state[0]), .Y (n_26));
  NOR3X1 g4181(.A (sound[1]), .B (disp[2]), .C (disp[1]), .Y (n_12));
  NAND3X1 g4182(.A (state[2]), .B (state[1]), .C (sound[0]), .Y (n_18));
  XNOR2X1 g4183(.A (count[0]), .B (count[1]), .Y (n_2));
  NAND2X1 g4184(.A (state[2]), .B (state[0]), .Y (n_20));
  NOR2X1 g4185(.A (state[3]), .B (open), .Y (n_13));
  AND2XL g4188(.A (count[1]), .B (count[0]), .Y (n_4));
  NOR2X1 g4187(.A (reduce_bal), .B (disp[0]), .Y (n_8));
  INVXL g4192(.A (rst), .Y (n_78));
  INVX1 g4193(.A (reduce_bal), .Y (n_38));
  INVX1 g4194(.A (state[1]), .Y (n_35));
  INVX1 g4190(.A (sound[0]), .Y (n_31));
  INVX1 g4191(.A (disp[1]), .Y (n_23));
  INVX1 g4195(.A (open), .Y (n_3));
  INVX1 drc_bufs4212(.A (n_36), .Y (n_47));
  INVX1 drc_bufs4216(.A (n_112), .Y (n_110));
  INVX1 drc_bufs4218(.A (n_39), .Y (n_112));
  NAND4BX1 g2(.AN (n_17), .B (state[0]), .C (state[1]), .D (n_28), .Y
       (n_122));
  NAND4BX1 g4228(.AN (disp[2]), .B (sound[1]), .C (n_23), .D (n_9), .Y
       (n_123));
  NAND2BX1 g4229(.AN (state[2]), .B (state[3]), .Y (n_124));
  NOR3BX1 g4230(.AN (n_47), .B (fund_enough), .C (monthly), .Y (n_125));
endmodule

